version: '3.8'

services:
  # Development service
  app-dev:
    container_name: bonboncar-cms-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

  # Production service
  app-prod:
    container_name: bonboncar-cms-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    restart: unless-stopped
