import type { BookingStatus } from '@/schemas/enum.schemas'

export const statusDisplay: Record<BookingStatus, string> = {
  ALL: 'Tất cả',
  DRAFT: 'Mới',
  PENDING: 'Chờ xử lý',
  CONFIRMED: 'Đã xác nhận',
  CANCELLED: 'Đã hủy',
  BOOKED: 'Đã giữ chỗ',
  VERIFYING: 'Đang xác minh',
  VERIFIED: 'Đã xác minh',
  CONTRACT_SIGNED: 'Đã ký HĐ',
  DEPOSIT: 'Đã cọc',
  ISBOOKING: 'Đang trong chuyến',
  RENTER_CHECKED_OUT: 'Người thuê trả xe',
  HOST_CHECKED_OUT: 'Chủ xe nhận xe',
  FEE_VERIFIED: 'Đã xác minh phí',
  HOST_VERIFIED: 'Chủ xe đã xác minh phí',
  RENTER_VERIFIED: 'Khách đã xác minh phí',
  COMPLETED: 'Hoàn thành',
  CANCEL: 'Đã hủy',
  NO_DEPOSIT: 'Không cọc',
}

export const statusColors: Record<BookingStatus, string> = {
  ALL: 'bg-gray-100 text-gray-800 border-gray-200',
  DRAFT: 'bg-blue-100 text-blue-800 border-blue-200',
  PENDING: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  CONFIRMED: 'bg-blue-100 text-blue-800 border-blue-200',
  CANCELLED: 'bg-red-100 text-red-800 border-red-200',
  BOOKED: 'bg-green-100 text-green-800 border-green-200',
  VERIFYING: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  VERIFIED: 'bg-purple-100 text-purple-800 border-purple-200',
  CONTRACT_SIGNED: 'bg-indigo-100 text-indigo-800 border-indigo-200',
  DEPOSIT: 'bg-orange-100 text-orange-800 border-orange-200',
  ISBOOKING: 'bg-cyan-100 text-cyan-800 border-cyan-200',
  RENTER_CHECKED_OUT: 'bg-pink-100 text-pink-800 border-pink-200',
  HOST_CHECKED_OUT: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  FEE_VERIFIED: 'bg-lime-100 text-lime-800 border-lime-200',
  COMPLETED: 'bg-green-100 text-green-800 border-green-200',
  CANCEL: 'bg-red-100 text-red-800 border-red-200',
  NO_DEPOSIT: 'bg-gray-100 text-gray-800 border-gray-200',
  HOST_VERIFIED: 'bg-green-100 text-green-800 border-green-200',
  RENTER_VERIFIED: 'bg-green-100 text-green-800 border-green-200',
}

export const buttonStatusDisplay: Record<
  BookingStatus,
  { label: string; pending: string; dialogTitle: string; dialogDesc: string; actionKey: string; color: string }
> = {
  ALL: {
    label: 'Tất cả',
    pending: 'Tất cả',
    dialogTitle: 'Tất cả',
    dialogDesc: 'Tất cả',
    actionKey: 'all',
    color: 'bg-gray-100 text-gray-800 border-gray-200',
  },
  DRAFT: {
    label: 'Xác nhận đặt xe',
    pending: 'Đang xác nhận',
    dialogTitle: 'Xác nhận đặt xe',
    dialogDesc: 'Bạn có chắc chắn muốn xác nhận đặt xe này?',
    actionKey: 'book',
    color: 'bg-blue-100 text-blue-800 border-blue-200',
  },
  BOOKED: {
    label: 'Đã giữ chỗ',
    pending: 'Đang xác nhận',
    dialogTitle: 'Đã giữ chỗ',
    dialogDesc: 'Bạn có chắc chắn muốn đã giữ chỗ này?',
    actionKey: 'book',
    color: 'bg-green-100 text-green-800 border-green-200',
  },
  VERIFYING: {
    label: 'Xác nhận đã ký HĐ',
    pending: 'Đang xác nhận',
    dialogTitle: 'Xác nhận đã ký HĐ',
    dialogDesc: 'Bạn có chắc chắn muốn xác nhận đã ký HĐ này?',
    actionKey: 'sign',
    color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  },
  VERIFIED: {
    label: 'Xác nhận tiền thuê và cọc',
    pending: 'Đang xác nhận',
    dialogTitle: 'Xác nhận tiền thuê và cọc',
    dialogDesc: 'Bạn có chắc chắn muốn xác nhận tiền thuê và cọc này?',
    actionKey: 'deposit',
    color: 'bg-purple-100 text-purple-800 border-purple-200',
  },
  CONTRACT_SIGNED: {
    label: 'Xác nhận chủ xe đã kiểm tra xe',
    pending: 'Đang xác nhận',
    dialogTitle: 'Xác nhận chủ xe đã kiểm tra xe',
    dialogDesc: 'Bạn có chắc chắn muốn xác nhận chủ xe đã kiểm tra xe này?',
    actionKey: 'sign',
    color: 'bg-indigo-100 text-indigo-800 border-indigo-200',
  },
  DEPOSIT: {
    label: 'Xác nhận tiền thuê và cọc',
    pending: 'Đang xác nhận',
    dialogTitle: 'Xác nhận tiền thuê và cọc',
    dialogDesc: 'Bạn có chắc chắn muốn xác nhận tiền thuê và cọc này?',
    actionKey: 'deposit',
    color: 'bg-orange-100 text-orange-800 border-orange-200',
  },
  ISBOOKING: {
    label: 'Xác nhận chủ xe đã kiểm tra xe',
    pending: 'Đang xác nhận',
    dialogTitle: 'Xác nhận chủ xe đã kiểm tra xe',
    dialogDesc: 'Bạn có chắc chắn muốn xác nhận chủ xe đã kiểm tra xe này?',
    actionKey: 'sign',
    color: 'bg-cyan-100 text-cyan-800 border-cyan-200',
  },
  RENTER_CHECKED_OUT: {
    label: 'Xác nhận chủ xe đã kiểm tra xe',
    pending: 'Đang xác nhận',
    dialogTitle: 'Xác nhận chủ xe đã kiểm tra xe',
    dialogDesc: 'Bạn có chắc chắn muốn xác nhận chủ xe đã kiểm tra xe này?',
    actionKey: 'sign',
    color: 'bg-pink-100 text-pink-800 border-pink-200',
  },
  HOST_CHECKED_OUT: {
    label: 'Xác nhận chủ xe đã kiểm tra xe',
    pending: 'Đang xác nhận',
    dialogTitle: 'Xác nhận chủ xe đã kiểm tra xe',
    dialogDesc: 'Bạn có chắc chắn muốn xác nhận chủ xe đã kiểm tra xe này?',
    actionKey: 'sign',
    color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  },
  FEE_VERIFIED: {
    label: 'Xác minh phí cho chủ xe',
    pending: 'Đang xác minh',
    dialogTitle: 'Xác minh phí cho chủ xe',
    dialogDesc: 'Bạn có chắc chắn muốn xác minh phí cho chủ xe này?',
    actionKey: 'fee',
    color: 'bg-lime-100 text-lime-800 border-lime-200',
  },
  HOST_VERIFIED: {
    label: 'Xác minh phí cho khách',
    pending: 'Đang xác minh',
    dialogTitle: 'Xác minh phí cho khách',
    dialogDesc: 'Bạn có chắc chắn muốn xác minh phí cho khách này?',
    actionKey: 'fee',
    color: 'bg-green-100 text-green-800 border-green-200',
  },
  RENTER_VERIFIED: {
    label: 'Xác minh phí cho khách',
    pending: 'Đang xác minh',
    dialogTitle: 'Xác minh phí cho khách',
    dialogDesc: 'Bạn có chắc chắn muốn xác minh phí cho khách này?',
    actionKey: 'fee',
    color: 'bg-green-100 text-green-800 border-green-200',
  },
  COMPLETED: {
    label: 'Hoàn thành',
    pending: 'Đang hoàn thành',
    dialogTitle: 'Hoàn thành',
    dialogDesc: 'Bạn có chắc chắn muốn hoàn thành này?',
    actionKey: 'complete',
    color: 'bg-green-100 text-green-800 border-green-200',
  },
  CANCEL: {
    label: 'Hủy',
    pending: 'Đang hủy',
    dialogTitle: 'Hủy',
    dialogDesc: 'Bạn có chắc chắn muốn hủy này?',
    actionKey: 'cancel',
    color: 'bg-red-100 text-red-800 border-red-200',
  },
  NO_DEPOSIT: {
    label: 'Không cọc',
    pending: 'Đang không cọc',
    dialogTitle: 'Không cọc',
    dialogDesc: 'Bạn có chắc chắn muốn không cọc này?',
    actionKey: 'no_deposit',
    color: 'bg-gray-100 text-gray-800 border-gray-200',
  },
  PENDING: {
    label: 'Chờ xử lý',
    pending: 'Đang chờ xử lý',
    dialogTitle: 'Chờ xử lý',
    dialogDesc: 'Bạn có chắc chắn muốn chờ xử lý này?',
    actionKey: 'pending',
    color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  },
  CONFIRMED: {
    label: 'Đã xác nhận',
    pending: 'Đang xác nhận',
    dialogTitle: 'Đã xác nhận',
    dialogDesc: 'Bạn có chắc chắn muốn xác nhận này?',
    actionKey: 'confirm',
    color: 'bg-blue-100 text-blue-800 border-blue-200',
  },
  CANCELLED: {
    label: 'Đã hủy',
    pending: 'Đang hủy',
    dialogTitle: 'Đã hủy',
    dialogDesc: 'Bạn có chắc chắn muốn hủy này?',
    actionKey: 'cancel',
    color: 'bg-red-100 text-red-800 border-red-200',
  },
}
