export const COLUMN_LABELS = {
  booking_id: 'Mã đơn đặt xe',
  scheduled_pickup_timestamp: 'Ngày giờ lấy xe',
  scheduled_return_timestamp: 'Ngày giờ trả xe',
  count_time: 'Thời gian đặt xe',
  car_sku: 'Mã xe',
  amount_to_pay: 'Tổng tiền',
  client: 'ekyc khách hàng',
  phone_number: 'SĐT',
  user_name: 'Tên khách hàng',
  status: 'Trạng thái',
  reason_of_cancel: 'Lý do huỷ',
  booking_type: 'Loại đơn đặt xe',
  discount: 'Giảm giá',
  delivery_option: 'Phương thức giao xe',
  delivery_address_to_cust: 'Địa chỉ giao xe',
  delivery_address_from_cust: 'Địa chỉ nhận xe chiều về',
  rental_amount: 'Tiền thuê xe',
  delivery_fee_amount_to_customer: 'Phí giao xe',
  deposit_amount: 'Tiền cọc',
  vat: 'Tiền VAT',
  platform: 'Nền tảng',
  promotion_code: 'Mã khuyến mãi',
  tag: 'Tag',
  user_city: 'Thành phố',
  is_export_vat: 'Xuất hoá đơn VAT',
  company_name: 'Tên công ty',
  company_address: 'Địa chỉ công ty',
  company_tax_code: 'Mã số thuế',
  company_email: 'Email công ty',
  purpose: 'Mục đích',
  itinerary: 'Lộ trình',
  created_at: 'Ngày giờ đặt',
  count_client_booking: 'Khách hàng',
} as const
